use_frameworks!

platform :ios, '9.0'

target 'PrivateCocoaModuleTwo_Example' do
  pod 'PrivateCocoaModuleTwo', :path => '../'

  target 'PrivateCocoaModuleTwo_Tests' do
    inherit! :search_paths

    
  end
end
